### ISSUE TITLE
nvimMd: rpc process is not executable

### ISSUE THREAD

**Issue by KestrelSoftworks** [oknozor/illumination#16]
Deployment via vim-plug seems to work, the path directories are created and the content is inside.
However, with both a new file and a previously saved file, each time I run ```:Illuminate``` this error happens:
```
Error detected while processing function <SNR>9_render:
line    5:
nvimMd: rpc process is not executable
```

**Comment by pearcedom** [comment]
Same issue here as well

**Comment by cosmoduff** [comment]
I ran into this issue as well. When I investigated further it seems the illuminate rust binary was never built and therefore was not executable. I tried building manually but then ran into error number 17.  I tried building with the latest stable rust 1.41.

**Comment by ShiinaScripts** [comment]
Also got the issue, hoping someone clever can fix it soon

**Comment by oknozor** [comment]
Hey sorry for the delay, I don't why I don't get notifications for this repo. I am going to look into this asap. I think it would be much easier to release a binary instead of building from source. If any one wants to help PRs are very welcome.

**Comment by oknozor** [comment]
Hey @pearcedom, @Seyeumi, @KestrelSoftworks I was able to reproduce your bug. I will work on a proper packaging for Illumination when I have some spare time. Meanwhile you can fix this by adding `$HOME/.cargo/bin` to your path, as explained in bf7d746f6c4cd16dec243a77c7ff47996497d85d.

**Comment by ShiinaScripts** [comment]
I have cargo in my path and it still isn't working, getting same error. Installed manually and added it to plugins.vim
