### ISSUE TITLE
Does It Support Showing Latex Equations?

### ISSUE THREAD

**Issue by eeriemyxi** [oknozor/illumination#20]
I was planning to use it for my mathematics notes, so I thought I'd ask. Also, is this project still maintained?

**Comment by oknozor** [comment]
Hey @eeriemyxi I am not maintaining this crate anymore. 

Internally illumination use [pulldown-cmark](https://github.com/pulldown-cmark/pulldown-cmark/) to render markdown. I am not sure latex is supported out of the box but if it is, implementing math support would be easy. You are welcome to submit a PR.

**Comment by oknozor** [comment]
https://github.com/pulldown-cmark/pulldown-cmark/releases/tag/v0.11.0

**Comment by eeriemyxi** [comment]
Thanks for the news.

**Comment by eeriemyxi** [comment]
Hi @oknozor, I tried compiling it and I am getting a bunch of errors after it compiled all the dependencies. I think the issue is with the compiler version. Do you happen to know which version is known to work? Mine is `1.75` (`rustc`).

**Comment by oknozor** [comment]
Hey, I just pushed a quick fix for the compilation and added mathjax to the webview dependencies (note that for now its pulled over http). 

Below is an example of the rendered result. As you can see inline math doesn't work (no idea why). 

![image](https://github.com/oknozor/illumination/assets/24563836/f567c466-b480-4c7c-a3c6-5867781e83e7)

**Comment by eeriemyxi** [comment]
Thanks for the update. I will try compiling it again in my free time later. I did some quick digging, and according to [this](https://tex.stackexchange.com/a/27656), inline notation would work if you did the config init of Mathjax _before_ loading it. Contrary to what you did [here](https://github.com/oknozor/illumination/blob/1f0c985eebab930126809e1aa3c9a8992daee3e8/src/preview.rs#L34-L40).
